### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by adamssski** [Jamiewarb/tea-bot#15]
I'm getting this error:

Darn – that didn't work (error message: `Timeout was reached`)

p.s. Love the bot!

**Comment by Jamiewarb** [comment]
Hey!

Could you let me know what happens when you get this error? Is it just from setting up the bot initially, or is it from specific events? Or maybe it just happens intermittently while it's running?

Glad you like it! I didn't know anyone else had actually seen it, so it's great to hear it has someone that wants to use it!

**Comment by adamssski** [comment]
Sorry, this actually only happens when you press one of the buttons from an old response. It's normally fine!

as an aside, is there some way to see how people have rated your brews?

**Comment by Jamiewarb** [comment]
Okay, glad to hear that! :)

And for your second question, not yet - brew rating is a secret so that you can rate negatively in confidence and anonymity. However, you can send 'displayRatings' in a direct message to the bot to see the total Up and Downs. Though this was originally for debug, so it's not formatted.
